Repository asyncapi/html-template, pull requests merged in 2022-03, with the labels that each got.

#329 chore: replace @github-actions[bot] with @asyncapi-bot-eve
  CODEOWNERS
Labels: area/ci-cd

#332 docs: update README.md logo banner #331
  README.md
  assets/github-repobanner-htmltemp.png
Labels: ready-to-merge

#333 chore: add info about maintainers
  .all-contributorsrc
  README.md
  package-lock.json
  package.json
Labels: ready-to-merge, 📑 docs
